name: flutter_starter_project
description: "A flutter starting template for new project (clean architecture+bloc/cubit)"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.10.4"
  flutter: ">=3.38.5"
dependencies:
  connectivity_plus: 7.0.0
  cupertino_icons: 1.0.8
  dio: 5.9.0
  drift: 2.30.1
  drift_flutter: 0.2.8
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  flutter_dotenv: 6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.4.7
  flutter_screenutil: 5.9.3
  flutter_secure_storage: 10.0.0
  freezed_annotation: 3.1.0
  get_it: 9.2.0
  go_router: 17.0.1
  google_fonts: 7.0.2
  internet_connection_checker_plus: 2.9.1+2
  intl: 0.20.2
  json_annotation: 4.9.0
  logger: 2.6.2
  nested: any
  path: 1.9.1
  path_provider: 2.1.5
  pretty_dio_logger: 1.4.0
  retrofit: 4.9.2
  shared_preferences: 2.5.4
dev_dependencies:
  build_runner: 2.10.5
  drift_dev: 2.30.1
  flutter_gen_runner: 5.12.0
  flutter_launcher_icons: 0.14.4
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.2.4
  json_serializable: 6.11.4
  retrofit_generator: 10.2.1


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/.env